import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { clearSession, createSession, currentUser, hashPassword, validatePassword, verifyPassword } from '@/lib/auth';
import { getDb, sqlNow, type Row } from '@/lib/db';
import { createGame, gameState, play, simpleAction } from '@/lib/game-service';
export const runtime='nodejs';export const dynamic='force-dynamic';
const ok=(data:unknown)=>NextResponse.json({ok:true,data});const fail=(message:string,status=400)=>NextResponse.json({ok:false,error:message},{status});
export async function POST(req:NextRequest){try{const input=await req.json().catch(()=>({}));const action=String(input.action||'');const db=await getDb();
if(action==='register'){const x=z.object({username:z.string().trim().min(3).max(24).regex(/^[\p{L}\p{N}_-]+$/u),password:z.string()}).parse(input);if(!validatePassword(x.password))return fail('Le mot de passe doit contenir 10 caractères, une majuscule, une minuscule, un chiffre et un symbole.');const r=await db.execute('INSERT INTO users(username,password_hash) VALUES(?,?)',[x.username,await hashPassword(x.password)]);await createSession({id:r.insertId,username:x.username});return ok({user:{id:r.insertId,username:x.username}})}
if(action==='login'){const x=z.object({username:z.string(),password:z.string()}).parse(input);const u=(await db.query<Row>('SELECT id,username,password_hash FROM users WHERE username=?',[x.username]))[0];if(!u||!await verifyPassword(x.password,String(u.password_hash)))return fail('Identifiants invalides.',401);await db.execute(`UPDATE users SET last_seen=${sqlNow()} WHERE id=?`,[u.id]);await createSession({id:Number(u.id),username:String(u.username)});return ok({user:{id:Number(u.id),username:String(u.username)}})}
if(action==='logout'){await clearSession();return ok(null)}const user=await currentUser();if(!user)return fail('Authentification requise.',401);
if(action==='dashboard'){const games=await db.query<Row>('SELECT g.id,g.status,g.mode,g.current_player_id,g.winner_id,g.created_at,MAX(CASE WHEN gp.user_id<>? THEN u.username END) opponent FROM games g JOIN game_players me ON me.game_id=g.id AND me.user_id=? LEFT JOIN game_players gp ON gp.game_id=g.id LEFT JOIN users u ON u.id=gp.user_id GROUP BY g.id ORDER BY g.id DESC LIMIT 30',[user.id,user.id]);const online=await db.query<Row>('SELECT id,username,wins,losses,draws FROM users WHERE id<>? ORDER BY username',[user.id]);const invites=await db.query<Row>("SELECT i.*,u.username from_username FROM invitations i JOIN users u ON u.id=i.from_user_id WHERE i.to_user_id=? AND i.status='pending' ORDER BY i.id DESC",[user.id]);const leaders=await db.query<Row>('SELECT id,username,wins,losses,draws FROM users ORDER BY wins DESC,draws DESC,username LIMIT 10');const me=(await db.query<Row>('SELECT id,username,wins,losses,draws FROM users WHERE id=?',[user.id]))[0];return ok({user:me,games,online,invites,leaders})}
if(action==='invite'){const x=z.object({toUserId:z.number().int().positive(),mode:z.enum(['free','timer']),timeLimit:z.number().int().min(1).max(120),increment:z.number().int().min(0).max(120)}).parse(input);if(x.toUserId===user.id)return fail('Vous ne pouvez pas vous inviter.');await db.execute("INSERT INTO invitations(from_user_id,to_user_id,status,mode,time_limit,increment_seconds) VALUES(?,?,'pending',?,?,?)",[user.id,x.toUserId,x.mode,x.timeLimit,x.increment]);return ok(null)}
if(action==='respondInvite'){const x=z.object({inviteId:z.number().int().positive(),accept:z.boolean()}).parse(input);const inv=(await db.query<Row>("SELECT * FROM invitations WHERE id=? AND to_user_id=? AND status='pending'",[x.inviteId,user.id]))[0];if(!inv)return fail('Invitation introuvable.');if(!x.accept){await db.execute("UPDATE invitations SET status='declined' WHERE id=?",[x.inviteId]);return ok(null)}const gameId=await createGame(Number(inv.from_user_id),user.id,String(inv.mode)==='timer'?'timer':'free',Number(inv.time_limit),Number(inv.increment_seconds));await db.execute("UPDATE invitations SET status='accepted' WHERE id=?",[x.inviteId]);return ok({gameId})}
if(action==='createSolo'){const x=z.object({mode:z.enum(['free','timer']),timeLimit:z.number().int().min(1).max(120),increment:z.number().int().min(0).max(120)}).parse(input);return ok({gameId:await createGame(user.id,null,x.mode,x.timeLimit,x.increment,true)})}
if(action==='state'){const x=z.object({gameId:z.number().int().positive()}).parse(input);return ok(await gameState(x.gameId,user.id))}
if(action==='play'){const x=z.object({gameId:z.number().int().positive(),version:z.number().int().positive(),placements:z.array(z.object({row:z.number().int().min(0).max(14),col:z.number().int().min(0).max(14),tileId:z.string().min(1),letter:z.string().length(1),blank:z.boolean().optional()})).min(1).max(7)}).parse(input);return ok(await play(x.gameId,user.id,x.placements,x.version))}
if(action==='gameAction'){const x=z.object({gameId:z.number().int().positive(),version:z.number().int().positive(),kind:z.enum(['pass','resign','exchange']),tileIds:z.array(z.string()).max(7).default([])}).parse(input);await simpleAction(x.gameId,user.id,x.kind,x.tileIds,x.version);return ok(null)}return fail('Action inconnue.',404)}catch(error){console.error(error);if(error instanceof z.ZodError)return fail('Données invalides.');return fail(error instanceof Error?error.message:'Erreur interne',500)}}
