<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scrabble Français - Partie</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="page-game">
    <div class="container game-page">
        <div class="game-layout">
            <div class="game-main">
                <div class="glass-card game-header">
                    <div class="game-scores">
                        <span id="player1-name">J1</span>: <strong id="player1-score">0</strong> <span id="p1-timer" class="timer">(00:00)</span>
                        <span class="vs">vs</span>
                        <span id="player2-name">J2</span>: <strong id="player2-score">0</strong> <span id="p2-timer" class="timer">(00:00)</span>
                    </div>
                    <div>
                        <div id="game-status">En attente...</div>
                        <div id="turn-badge" class="turn-badge" style="display:none;">Hors tour</div>
                    </div>
                    <div style="display:flex; gap:8px;">
                        <button id="mobile-history-toggle" class="mobile-history-toggle" type="button">Historique</button>
                        <button id="board-zoom-toggle" class="sound-toggle" type="button">Zoom plateau</button>
                        <button id="sound-toggle" class="sound-toggle" type="button">Son: ON</button>
                        <button class="btn-ghost" onclick="window.location.href='dashboard.php'">Quitter</button>
                    </div>
                </div>

                <div id="game-container">
                    <div id="board">
                        <!-- Grid generated by JS -->
                    </div>
                </div>

                <div id="rack" class="glass-card">
                    <!-- Rack tiles generated by JS -->
                </div>

                <div id="exchange-banner" class="exchange-banner" style="display:none;">
                    Sélectionnez des lettres à échanger, puis confirmez.
                </div>

                <div class="game-actions">
                    <button id="btn-submit" onclick="submitMove()">Valider</button>
                    <button id="btn-recall" onclick="recallTiles()">Rappeler</button>
                    <button id="btn-shuffle" onclick="shuffleRack()">Mélanger</button>
                    <button id="btn-exchange" onclick="toggleExchangeMode()">Échanger</button>
                    <button id="btn-cancel-exchange" onclick="cancelExchangeMode()" class="btn-muted" style="display:none;">Annuler échange</button>
                    <button id="btn-pass" onclick="passTurn()" class="btn-muted">Passer</button>
                    <button id="btn-resign" onclick="resignGame()" class="btn-danger">Abandonner</button>
                </div>
            </div>

            <div id="sidebar" class="glass-card game-sidebar">
                <h3>Historique</h3>
                <div id="history-log" class="history-log">
                    <!-- Moves log -->
                </div>
                
                <hr class="divider">
                
                <div id="tile-bag-info">
                    Pièces restantes: <span id="bag-count">--</span>
                </div>

                <div class="score-preview">
                    <div class="muted">Score potentiel</div>
                    <div id="preview-score">0</div>
                    <div id="preview-note" class="muted" style="font-size:0.85rem;"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="validation-modal" class="glass-card modal" style="display:none;">
        <h3 id="validation-msg">Validation...</h3>
        <button onclick="document.getElementById('validation-modal').style.display='none'">Fermer</button>
    </div>

    <!-- Mobile Drawer -->
    <div id="history-drawer" class="drawer">
        <div class="drawer-handle"></div>
        <div class="drawer-header">
            <strong>Historique</strong>
            <button class="btn-muted" onclick="closeHistoryDrawer()">Fermer</button>
        </div>
        <div id="history-log-drawer" class="history-log"></div>
    </div>

    <!-- Profile Modal -->
    <div id="profile-modal" class="glass-card modal" style="display:none;">
        <h3 id="profile-title">Profil</h3>
        <div id="profile-stats" class="profile-grid"></div>
        <div id="profile-history" style="margin-top:12px;"></div>
        <div class="modal-actions" style="margin-top: 12px;">
            <button class="btn-muted" onclick="closeProfileModal()">Fermer</button>
        </div>
    </div>

    <script src="js/app.js"></script>
    <script src="js/game.js"></script>
</body>
</html>
