import { createClient, type Client } from '@libsql/client';
import mysql, { type Pool, type PoolConnection } from 'mysql2/promise';
export type Row=Record<string,unknown>;
export type Db={query<T extends Row>(sql:string,params?:unknown[]):Promise<T[]>;execute(sql:string,params?:unknown[]):Promise<{insertId:number;affectedRows:number}>;transaction<T>(fn:(db:Db)=>Promise<T>):Promise<T>};
let singleton:Promise<Db>|null=null;
function sqliteDb(client:Client):Db{return{async query<T extends Row>(sql,params=[]){const r=await client.execute({sql,args:params as never[]});return r.rows as unknown as T[];},async execute(sql,params=[]){const r=await client.execute({sql,args:params as never[]});return{insertId:Number(r.lastInsertRowid??0),affectedRows:r.rowsAffected};},async transaction<T>(fn){const tx=await client.transaction('write');const db=sqliteDb(tx as unknown as Client);try{const value=await fn(db);await tx.commit();return value;}catch(e){await tx.rollback();throw e;}}};}
function mysqlConnectionDb(connection:Pool|PoolConnection):Db{return{async query<T extends Row>(sql,params=[]){const[rows]=await connection.query(sql,params);return rows as T[];},async execute(sql,params=[]){const[result]=await connection.execute(sql,params) as [{insertId:number;affectedRows:number},unknown];return result;},async transaction<T>(fn){if(!('getConnection'in connection))return fn(mysqlConnectionDb(connection));const c=await connection.getConnection();await c.beginTransaction();try{const value=await fn(mysqlConnectionDb(c));await c.commit();return value;}catch(e){await c.rollback();throw e;}finally{c.release();}}};}
async function initialize(){const type=(process.env.DB_TYPE??'sqlite').toLowerCase();const url=process.env.DATABASE_URL??'file:./data/scrabble-v2.db';const db=type==='mysql'?mysqlConnectionDb(mysql.createPool({uri:url,connectionLimit:5,enableKeepAlive:true})):sqliteDb(createClient({url}));const id=type==='mysql'?'BIGINT AUTO_INCREMENT PRIMARY KEY':'INTEGER PRIMARY KEY AUTOINCREMENT';const text=type==='mysql'?'LONGTEXT':'TEXT';const now=type==='mysql'?'CURRENT_TIMESTAMP':"CURRENT_TIMESTAMP";for(const statement of[
`CREATE TABLE IF NOT EXISTS users(id ${id},username VARCHAR(32) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,wins INTEGER NOT NULL DEFAULT 0,losses INTEGER NOT NULL DEFAULT 0,draws INTEGER NOT NULL DEFAULT 0,created_at DATETIME DEFAULT ${now},last_seen DATETIME DEFAULT ${now})`,
`CREATE TABLE IF NOT EXISTS games(id ${id},status VARCHAR(16) NOT NULL DEFAULT 'active',mode VARCHAR(16) NOT NULL DEFAULT 'free',is_solo INTEGER NOT NULL DEFAULT 0,current_player_id BIGINT,winner_id BIGINT,time_limit INTEGER NOT NULL DEFAULT 0,increment_seconds INTEGER NOT NULL DEFAULT 0,board ${text} NOT NULL,bag ${text} NOT NULL,version INTEGER NOT NULL DEFAULT 1,consecutive_scoreless INTEGER NOT NULL DEFAULT 0,last_move_at DATETIME DEFAULT ${now},created_at DATETIME DEFAULT ${now},ended_at DATETIME NULL)`,
`CREATE TABLE IF NOT EXISTS game_players(game_id BIGINT NOT NULL,user_id BIGINT NOT NULL,rack ${text} NOT NULL,score INTEGER NOT NULL DEFAULT 0,time_remaining INTEGER NOT NULL DEFAULT 0,turn_order INTEGER NOT NULL,PRIMARY KEY(game_id,user_id))`,
`CREATE TABLE IF NOT EXISTS moves(id ${id},game_id BIGINT NOT NULL,user_id BIGINT,kind VARCHAR(16) NOT NULL,words ${text},points INTEGER NOT NULL DEFAULT 0,placements ${text},created_at DATETIME DEFAULT ${now})`,
`CREATE TABLE IF NOT EXISTS invitations(id ${id},from_user_id BIGINT NOT NULL,to_user_id BIGINT NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'pending',mode VARCHAR(16) NOT NULL DEFAULT 'free',time_limit INTEGER NOT NULL DEFAULT 15,increment_seconds INTEGER NOT NULL DEFAULT 0,created_at DATETIME DEFAULT ${now})`
])await db.execute(statement);return db;}
export function getDb(){singleton??=initialize();return singleton;}
export function sqlNow(){return'CURRENT_TIMESTAMP';}
