import { multiplierAt } from './board';
import { LETTERS } from './tiles';
import type { Board, Placement, Tile } from './types';
export const emptyBoard=():Board=>Array.from({length:15},()=>Array(15).fill(null));
const inside=(n:number)=>n>=0&&n<15;const normalized=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
export type ValidationResult={valid:true;score:number;words:string[];board:Board}|{valid:false;error:string};
export function validateAndScore(board:Board,rack:Tile[],placements:Placement[],dictionary:Set<string>):ValidationResult{
 if(!placements.length)return{valid:false,error:'Posez au moins une lettre.'};if(placements.length>7)return{valid:false,error:'Un chevalet contient au maximum sept lettres.'};
 const seen=new Set<string>();const rackById=new Map(rack.map(t=>[t.id,t]));
 for(const p of placements){const k=`${p.row}:${p.col}`;if(!inside(p.row)||!inside(p.col)||seen.has(k)||board[p.row][p.col])return{valid:false,error:'Placement invalide ou case déjà occupée.'};const tile=rackById.get(p.tileId);if(!tile)return{valid:false,error:'Une lettre posée ne vient pas de votre chevalet.'};if(tile.letter==='*'&&!/^[A-Z]$/.test(normalized(p.letter)))return{valid:false,error:'Choisissez une lettre pour le joker.'};if(tile.letter!=='*'&&tile.letter!==normalized(p.letter))return{valid:false,error:'La lettre ne correspond pas à la tuile.'};seen.add(k);rackById.delete(p.tileId);}
 const rows=new Set(placements.map(p=>p.row)),cols=new Set(placements.map(p=>p.col));if(rows.size>1&&cols.size>1)return{valid:false,error:'Les lettres doivent être alignées.'};const horizontal=rows.size===1;const next=board.map(row=>[...row]);
 for(const p of placements){const original=rack.find(t=>t.id===p.tileId)!;next[p.row][p.col]={...original,letter:normalized(p.letter),blank:original.letter==='*'};}
 const wasEmpty=board.every(row=>row.every(cell=>!cell));if(wasEmpty&&!next[7][7])return{valid:false,error:'Le premier mot doit couvrir la case centrale.'};
 if(!wasEmpty){const touches=placements.some(p=>[[p.row-1,p.col],[p.row+1,p.col],[p.row,p.col-1],[p.row,p.col+1]].some(([r,c])=>inside(r)&&inside(c)&&board[r][c]));if(!touches)return{valid:false,error:'Le mot doit se raccorder au plateau.'};}
 const axis=placements.map(p=>horizontal?p.col:p.row),fixed=horizontal?placements[0].row:placements[0].col;for(let i=Math.min(...axis);i<=Math.max(...axis);i++)if(!next[horizontal?fixed:i][horizontal?i:fixed])return{valid:false,error:'Les lettres posées doivent former une ligne continue.'};
 const created=new Set(placements.map(p=>`${p.row}:${p.col}`));const readWord=(r:number,c:number,h:boolean)=>{let sr=r,sc=c;while(inside(h?sc-1:sr-1)&&next[h?sr:sr-1][h?sc-1:sc])h?sc--:sr--;const cells:Array<{r:number;c:number;tile:Tile}>=[];let rr=sr,cc=sc;while(inside(h?cc:rr)&&next[rr][cc]){cells.push({r:rr,c:cc,tile:next[rr][cc]!});h?cc++:rr++;}return cells;};
 const all=[readWord(placements[0].row,placements[0].col,horizontal),...placements.map(p=>readWord(p.row,p.col,!horizontal)).filter(c=>c.length>1)];const unique=new Map<string,typeof all[number]>();for(const cells of all)unique.set(cells.map(x=>`${x.r}:${x.c}`).join('|'),cells);
 const words:string[]=[];let score=0;for(const cells of unique.values()){const word=cells.map(x=>x.tile.letter).join('');if(word.length<2)return{valid:false,error:'Un mot doit contenir au moins deux lettres.'};if(!dictionary.has(normalized(word)))return{valid:false,error:`Mot non admis : ${word}`};let subtotal=0,wordMultiplier=1;for(const x of cells){let points=x.tile.blank?0:(LETTERS[x.tile.letter]?.points??x.tile.points);if(created.has(`${x.r}:${x.c}`)){const m=multiplierAt(x.r,x.c);if(m==='DL')points*=2;if(m==='TL')points*=3;if(m==='DW'||m==='ST')wordMultiplier*=2;if(m==='TW')wordMultiplier*=3;}subtotal+=points;}score+=subtotal*wordMultiplier;words.push(word);}if(placements.length===7)score+=50;return{valid:true,score,words,board:next};
}
